CREATE TABLE recipes (id SERIAL PRIMARY KEY, name TEXT, user_id INTEGER, visible BOOLEAN);
CREATE TABLE ingredients (id SERIAL PRIMARY KEY, name TEXT, recipe INTEGER);
CREATE TABLE steps (id SERIAL PRIMARY KEY, name TEXT, recipe INTEGER);
CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT, password TEXT);
CREATE TABLE friends (id SERIAL PRIMARY KEY, user1 INTEGER, user2 INTEGER);
CREATE TABLE friendrequests (id SERIAL PRIMARY KEY, sender INTEGER, receiver INTEGER, visible BOOLEAN);
